modLoader="javafml" #mandatory
loaderVersion="[36,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/wilyank/portable_beacons/issues/" #optional
[[mods]] #mandatory
modId="portable_beacons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Portable Beacons Mod" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/portable-beacons/" #optional
logoFile="logo.png" #optional
credits="Thanks to Herrscher of Banana for making some wonderful textures" #optional
authors="Wilyan Kramer" #optional
description='''
Carry a beacon on your back. Never be out of range!
This mod adds several Potion Effect-related items, including a Potion Necklace, an Infused Dagger and a Diffuser.
'''
itemIcon="portable_beacons:beacon_backpack_0"
[[dependencies.portable_beacons]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.20,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.portable_beacons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.portable_beacons]]
	modId="curios"
	mandatory=true
	versionRange="[1.16.5-4.0.5.2,)"
	ordering="NONE"
	side="BOTH"
[modproperties.portable_beacons]
    catalogueImageIcon="portable_beacons:beacon_backpack_0"
    configuredBackground="minecraft:textures/block/iron_block.png"